### ISSUE TITLE
CBERS4A/WFI and CBERS4/AWFI must check for {LEFT_RIGHT} xmls

### ISSUE THREAD

**Issue by fredliporace** [fredliporace/cbers-2-stac#94]
Same processing that is made for Amazonia-1

**Comment by fredliporace** [comment]
````
[ERROR] AssertionError: Can't find metadata for CBERS4A/WFI/222/148/CBERS_4A_WFI_20200626_222_148_L4/CBERS_4A_WFI_20200626_222_148_L4_BAND14.xml
Traceback (most recent call last):
  File "/var/task/code.py", line 420, in handler
    corrupted_xml_queue=os.environ["corrupted_xml_queue_url"],
  File "/var/task/code.py", line 310, in process_trigger
    catalog_update_table,
  File "/var/task/code.py", line 207, in process_message
    assert found, f"Can't find metadata for {metadata_keys['inpe_metadata']}"
```

**Comment by fredliporace** [comment]
Got two CBERS4/WFI cases, need to check left and right for this also.
